// Generates src/prompts.generated.ts from prompts/*.md so the prompt ships inside the bundle.
// The .md files are the source of truth; a test fails if the generated file is stale.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const entries = readdirSync(join(root, "prompts"))
  .filter((f) => f.endsWith(".md"))
  .sort()
  .map((f) => [f.replace(/\.md$/, ""), readFileSync(join(root, "prompts", f), "utf8")]);

const body = entries
  .map(([id, text]) => `  ${JSON.stringify(id)}: ${JSON.stringify(text)},`)
  .join("\n");
writeFileSync(
  join(root, "src", "prompts.generated.ts"),
  `// GENERATED by scripts/gen-prompts.mjs from prompts/*.md. Do not edit by hand.\nexport const PROMPTS: Record<string, string> = {\n${body}\n};\n`,
);
