// GENERATED by scripts/gen-knowledge.mjs from knowledge/{en,ar}/*.md. Do not edit by hand.
import type { KnowledgeEntry } from "./knowledge";

export const KNOWLEDGE: KnowledgeEntry[] = [
  {
    "id": "amil-data",
    "locale": "en",
    "title": "What data does AMIL use?",
    "keywords": [
      "amil",
      "data",
      "privacy",
      "consent",
      "ai",
      "personal data"
    ],
    "paragraphs": [
      "With your consent, AMIL reads your own Doha Demo Bank products and the bank's published rules to work out what you gain or lose. Every figure is calculated, not written by AI. If AI helps with the wording, it sees only the figures, never your name or account numbers.",
      "You can turn AMIL on or off in Settings at any time."
    ]
  },
  {
    "id": "annual-fee-refund",
    "locale": "en",
    "title": "Do I get part of the annual fee back if I close my card?",
    "keywords": [
      "annual fee",
      "refund",
      "close card",
      "cancel card",
      "pro rata"
    ],
    "paragraphs": [
      "If the card's terms allow it, part of the annual fee is refunded when you close the card, in proportion to the full months left in the card year.",
      "The exact refund for your card is shown before you confirm the closure."
    ]
  },
  {
    "id": "cash-withdrawal",
    "locale": "en",
    "title": "Why does a cash withdrawal on a credit card cost more?",
    "keywords": [
      "cash withdrawal",
      "cash advance",
      "atm",
      "credit card cash",
      "fee"
    ],
    "paragraphs": [
      "A cash withdrawal on a credit card has a fee, and charges apply from the day you withdraw, with no grace period. Purchases, by contrast, have no charges if you pay the full statement balance by the due date.",
      "Withdrawing with a debit card from your current account avoids these charges."
    ]
  },
  {
    "id": "dormancy",
    "locale": "en",
    "title": "What makes an account dormant?",
    "keywords": [
      "dormant",
      "dormancy",
      "inactive",
      "inactivity",
      "reactivate",
      "unused account"
    ],
    "paragraphs": [
      "An account becomes dormant when you have made no transactions on it for the bank's dormancy period. A dormant account is restricted until you reactivate it, but the balance stays yours.",
      "Any transaction you make, such as a transfer, deposit or card payment from the account, keeps it active. To reactivate a dormant account, contact the bank."
    ]
  },
  {
    "id": "ibra",
    "locale": "en",
    "title": "What is ibra when I settle a murabaha early?",
    "keywords": [
      "ibra",
      "rebate",
      "murabaha",
      "early settlement",
      "settle early",
      "profit"
    ],
    "paragraphs": [
      "Ibra is a rebate the bank gives on the deferred profit that is not yet due when you settle a murabaha early. The bank's policy sets the ibra rate, and it can increase as more instalments are paid.",
      "Because of this, the total you pay can be lower if you settle on a date after a rate change. AMIL checks each day in the coming weeks and shows the cheapest date."
    ]
  },
  {
    "id": "instalment-plans",
    "locale": "en",
    "title": "How do card instalment plans work?",
    "keywords": [
      "instalment plan",
      "installment",
      "epp",
      "convert purchase",
      "easy payment"
    ],
    "paragraphs": [
      "An instalment plan spreads a card purchase over several months. Plans usually have a processing fee, and closing a plan early can have a fee too. If you close the card, active plans become payable in full.",
      "Paying the purchase in full by the due date has no charge."
    ]
  },
  {
    "id": "minimum-payment",
    "locale": "en",
    "title": "What happens if I only pay the minimum?",
    "keywords": [
      "minimum payment",
      "minimum due",
      "pay minimum",
      "revolving",
      "balance"
    ],
    "paragraphs": [
      "Paying the minimum keeps your card in good standing, but the rest of the balance carries charges every month until it is paid. The smaller the payment, the longer it takes and the more you pay overall.",
      "Paying the full statement balance by the due date avoids these charges."
    ]
  },
  {
    "id": "reward-points",
    "locale": "en",
    "title": "When do reward points expire?",
    "keywords": [
      "points",
      "reward points",
      "rewards",
      "expire",
      "expiry",
      "redeem"
    ],
    "paragraphs": [
      "Reward points expire on the dates shown in your rewards summary, and points still on a card end when the card is closed. Redeeming before then keeps their value.",
      "AMIL sends an alert when points are close to expiring, if you allow proactive alerts."
    ]
  },
  {
    "id": "salary-transfer",
    "locale": "en",
    "title": "What is linked to my salary transfer?",
    "keywords": [
      "salary",
      "salary transfer",
      "move salary",
      "salary account",
      "waiver",
      "salary linked"
    ],
    "paragraphs": [
      "Some pricing and fee waivers depend on your salary being paid into the bank. Moving your salary elsewhere can change the instalments on salary-linked finance, and those waivers can end.",
      "AMIL shows exactly what is linked to your salary before you confirm a change."
    ]
  },
  {
    "id": "term-deposits",
    "locale": "en",
    "title": "What happens if I break a term deposit early?",
    "keywords": [
      "term deposit",
      "break deposit",
      "fixed deposit",
      "early withdrawal",
      "maturity",
      "term investment"
    ],
    "paragraphs": [
      "Breaking a term deposit before maturity usually pays a reduced return for the time it was held, and the bank may charge a break penalty. Keeping it to maturity pays the full agreed return.",
      "AMIL shows both side by side before you confirm."
    ]
  },
  {
    "id": "amil-data",
    "locale": "ar",
    "title": "ما البيانات التي يستخدمها عميل؟",
    "keywords": [
      "عميل",
      "بيانات",
      "الخصوصية",
      "الموافقة",
      "الذكاء الاصطناعي",
      "البيانات الشخصية"
    ],
    "paragraphs": [
      "بموافقتك، يقرأ عميل منتجاتك في بنك الدوحة التجريبي وقواعد البنك المنشورة ليحسب ما تكسبه أو تخسره. كل رقم محسوب ولا يكتبه الذكاء الاصطناعي، وإذا ساعد الذكاء الاصطناعي في الصياغة فإنه يرى الأرقام فقط، ولا يرى اسمك أو أرقام حساباتك.",
      "يمكنك تفعيل عميل أو إيقافه من الإعدادات في أي وقت."
    ]
  },
  {
    "id": "annual-fee-refund",
    "locale": "ar",
    "title": "هل أسترد جزءاً من الرسوم السنوية إذا أغلقت بطاقتي؟",
    "keywords": [
      "الرسوم السنوية",
      "استرداد",
      "إغلاق البطاقة",
      "إلغاء البطاقة",
      "نسبي"
    ],
    "paragraphs": [
      "إذا كانت شروط البطاقة تسمح بذلك، يُردّ جزء من الرسوم السنوية عند إغلاق البطاقة بنسبة الأشهر الكاملة المتبقية من سنة البطاقة.",
      "يظهر لك مبلغ الاسترداد الخاص ببطاقتك قبل تأكيد الإغلاق."
    ]
  },
  {
    "id": "cash-withdrawal",
    "locale": "ar",
    "title": "لماذا يكلّف السحب النقدي ببطاقة الائتمان أكثر؟",
    "keywords": [
      "السحب النقدي",
      "سحب نقدي",
      "صراف",
      "نقد البطاقة",
      "رسوم"
    ],
    "paragraphs": [
      "السحب النقدي ببطاقة الائتمان تترتب عليه رسوم، وتُحتسب التكاليف من يوم السحب دون فترة سماح. أما المشتريات فلا تترتب عليها رسوم إذا سددت كامل رصيد الكشف قبل تاريخ الاستحقاق.",
      "السحب ببطاقة الخصم من حسابك الجاري يجنّبك هذه الرسوم."
    ]
  },
  {
    "id": "dormancy",
    "locale": "ar",
    "title": "متى يصبح الحساب خاملاً؟",
    "keywords": [
      "خامل",
      "الخمول",
      "غير نشط",
      "إعادة تفعيل",
      "حساب غير مستخدم"
    ],
    "paragraphs": [
      "يصبح الحساب خاملاً عندما لا تُجري عليه أي معاملة طوال فترة الخمول التي يحددها البنك. يُقيَّد الحساب الخامل حتى تعيد تفعيله، لكن رصيده يبقى ملكك.",
      "أي معاملة تجريها، مثل تحويل أو إيداع أو سداد ببطاقة من الحساب، تُبقيه نشطاً. لإعادة تفعيل حساب خامل تواصل مع البنك."
    ]
  },
  {
    "id": "ibra",
    "locale": "ar",
    "title": "ما هو الإبراء عند السداد المبكر للمرابحة؟",
    "keywords": [
      "الإبراء",
      "خصم",
      "مرابحة",
      "السداد المبكر",
      "سداد مبكر",
      "الأرباح"
    ],
    "paragraphs": [
      "الإبراء خصم يمنحه البنك من الأرباح المؤجلة غير المستحقة بعد عند السداد المبكر للمرابحة. تحدد سياسة البنك نسبة الإبراء، وقد ترتفع كلما سُدّد عدد أكبر من الأقساط.",
      "لذلك قد يكون إجمالي ما تدفعه أقل إذا سددت في تاريخ بعد تغيّر النسبة. يفحص عميل كل يوم خلال الأسابيع القادمة ويعرض التاريخ الأقل تكلفة."
    ]
  },
  {
    "id": "instalment-plans",
    "locale": "ar",
    "title": "كيف تعمل خطط التقسيط على البطاقة؟",
    "keywords": [
      "خطة تقسيط",
      "تقسيط",
      "أقساط",
      "تحويل المشتريات"
    ],
    "paragraphs": [
      "خطة التقسيط توزّع قيمة مشتريات البطاقة على عدة أشهر، وعادةً تترتب عليها رسوم معالجة، وقد تترتب رسوم على إغلاقها مبكراً. وإذا أغلقت البطاقة تصبح الخطط القائمة مستحقة بالكامل.",
      "سداد المشتريات كاملة قبل تاريخ الاستحقاق لا تترتب عليه رسوم."
    ]
  },
  {
    "id": "minimum-payment",
    "locale": "ar",
    "title": "ماذا يحدث إذا سددت الحد الأدنى فقط؟",
    "keywords": [
      "الحد الأدنى",
      "الحد الأدنى المستحق",
      "سداد الحد الأدنى",
      "الرصيد المتبقي"
    ],
    "paragraphs": [
      "سداد الحد الأدنى يحافظ على انتظام بطاقتك، لكن باقي الرصيد تترتب عليه رسوم كل شهر حتى يُسدَّد. كلما قلّ المبلغ المسدد طالت المدة وزاد إجمالي ما تدفعه.",
      "سداد كامل رصيد الكشف قبل تاريخ الاستحقاق يجنّبك هذه الرسوم."
    ]
  },
  {
    "id": "reward-points",
    "locale": "ar",
    "title": "متى تنتهي صلاحية نقاط المكافآت؟",
    "keywords": [
      "نقاط",
      "نقاط المكافآت",
      "المكافآت",
      "انتهاء الصلاحية",
      "استبدال"
    ],
    "paragraphs": [
      "تنتهي صلاحية نقاط المكافآت في التواريخ الظاهرة في ملخص مكافآتك، والنقاط المتبقية على البطاقة تنتهي عند إغلاقها. الاستبدال قبل ذلك يحفظ قيمتها.",
      "يرسل عميل تنبيهاً عندما تقترب نقاطك من انتهاء صلاحيتها إذا سمحت بالتنبيهات الاستباقية."
    ]
  },
  {
    "id": "salary-transfer",
    "locale": "ar",
    "title": "ما الذي يرتبط بتحويل راتبي؟",
    "keywords": [
      "راتب",
      "تحويل الراتب",
      "نقل الراتب",
      "حساب الراتب",
      "إعفاء",
      "مرتبط بالراتب"
    ],
    "paragraphs": [
      "بعض الأسعار والإعفاءات من الرسوم مرتبطة بتحويل راتبك إلى البنك. نقل راتبك إلى جهة أخرى قد يغيّر أقساط التمويل المرتبط بالراتب وقد تنتهي تلك الإعفاءات.",
      "يعرض عميل ما يرتبط براتبك بالتحديد قبل أن تؤكد أي تغيير."
    ]
  },
  {
    "id": "term-deposits",
    "locale": "ar",
    "title": "ماذا يحدث إذا كسرت وديعة لأجل مبكراً؟",
    "keywords": [
      "وديعة لأجل",
      "كسر الوديعة",
      "وديعة ثابتة",
      "سحب مبكر",
      "الاستحقاق",
      "استثمار لأجل"
    ],
    "paragraphs": [
      "كسر الوديعة لأجل قبل استحقاقها يمنح عادةً عائداً أقل عن المدة التي بقيت فيها، وقد يفرض البنك غرامة كسر. أما إبقاؤها حتى الاستحقاق فيمنحك العائد المتفق عليه كاملاً.",
      "يعرض عميل الخيارين جنباً إلى جنب قبل أن تؤكد."
    ]
  }
];
